### ISSUE TITLE
public API

### ISSUE THREAD

**Issue by ijlyttle** [ijlyttle/pinsManifest#1]
The goal is to make something that fits with pins' existing [`pins::board_url()`](https://pins.rstudio.com/reference/board_url.html), using [`pins::board_folder()`](https://pins.rstudio.com/reference/board_folder.html), for now, as a source.

```r
# support pins::board_folder() only
pin_write_manifest <- function(board)

# wraps pins::board_url()
board_url_manifest <- function(url, cache = NULL, use_cache_on_failure = is_interactive())

# returns named vector of URLs to provide to pins::board_url()
manifest_latest <- function(url)
```

The idea is that you have a folder board that you wish to serve as a URL (perhaps using GitHub). 

Before deploying your board, you would call `pin_write_manifest()`, which would write a file `manifest.txt` to the root folder of the board.

Users of your URL board could use `board_url_manifest()` using the root URL. It would:
  - look for `manifest.txt`, download it
  - convert the manifest to a named vector of URLs for each pin (using the most-recent version for each pin)
  - use this named vector to create a `pins::board_url()`
  - return the board

The file `manifest.txt` would be a YAML file representing a named list, e.g.:

```yaml
penguins-json:
  - 20220805T214253Z-fa33e
  - 20220805T214254Z-faeee
penguins-arrow:
  - 20220805T214253Z-ca33e
  - 20220805T214254Z-caeee
```
